version: "3.8"

x-spark-common: &spark-common
  image: bitnami/spark:3.5.0
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    - ./data:/opt/bitnami/spark/data
    - ./jars:/opt/bitnami/spark/external_jars
  depends_on:
    - spark-master
  environment:
    SPARK_MODE: worker
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_MASTER_URL: spark://spark-master:7077
    PYARROW_IGNORE_TIMEZONE: "1"
    SPARK_OPTS: --jars /opt/bitnami/spark/external_jars/*.jar
  networks:
    - pyspark-network

services:
  spark-master:
    image: bitnami/spark:3.5.0
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./data:/opt/bitnami/spark/data
      - ./jars:/opt/bitnami/spark/external_jars
    environment:
      SPARK_OPTS: --jars /opt/bitnami/spark/external_jars/*.jar
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master Port
    networks:
      - pyspark-network

  spark-worker-1:
    <<: *spark-common

  spark-worker-2:
    <<: *spark-common

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    ports:
      - "8888:8888"  # JupyterLab UI
      - "4040:4040"  # JupyterSpark UI
    volumes:
      - ./jobs:/home/jovyan/work/jobs
      - ./data:/home/jovyan/work/data
      - ./jars:/home/jovyan/work/jars
      - ./notebooks:/home/jovyan/work/notebooks
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      SPARK_MASTER: "spark://spark-master:7077"
      PYSPARK_SUBMIT_ARGS: "--master spark://spark-master:7077 --jars /home/jovyan/work/jars/*.jar pyspark-shell"
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    networks:
      - pyspark-network

networks:
  pyspark-network:
    driver: bridge
